#agent_onprem.conf
<agent_config>
  <syscheck>
    <directories realtime="yes" check_all="yes" report_changes="yes">/host/etc</directories>
    <directories realtime="yes" check_all="yes">/host/home/mspadmin</directories>
    <ignore>/host/etc/mtab</ignore>
    <ignore>/host/etc/resolv.conf</ignore>
    <ignore>/host/etc/adjtime</ignore>
  </syscheck>

  <localfile>
    <log_format>syslog</log_format>
    <location>/host/var/log/auth.log</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/host/var/log/syslog</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/host/var/log/ufw.log</location>
  </localfile>
  <localfile>
    <log_format>apache</log_format>
    <location>/host/var/log/deident/nginx/access.log</location>
  </localfile>
  <localfile>
    <log_format>apache</log_format>
    <location>/host/var/log/deident/nginx/error.log</location>
  </localfile>
  <localfile>
    <log_format>json</log_format>
    <location>/host/var/log/deident/audit.log</location>
  </localfile>
  <localfile>
    <log_format>json</log_format>
    <location>/host/var/log/deident/db_audit.log</location>
  </localfile>
  <localfile>
  <log_format>json</log_format>
  <location>/host/vault-data/audit.log</location>
</localfile>
</agent_config>